### ISSUE TITLE
Confused with binning output file

### ISSUE THREAD

**Issue by FilipeMatteoli** [Vini2/GraphBin#11]
Hello, thanks for the exciting tool.
I would like to try out the tool but I am not sure about the requested binning file.

I tried using the prepResult.py script but I suspect the output is wrong. As input, I used the folder of the SPAdes output (metasample1/metaSpades). I ran it as following
`python prepResult.py --binned 'metasample1/metaSpades' --assembler SPAdes --output 'metasample1/metaSpades/z_graphbin'`

The following message was sent to stdout:
Formatting initial binning results

Writing initial binning results to output file

Formatted initial binning results can be found at /metasample1/metaSpades/z_graphbin/initial_contig_bins.csv

Bin IDs and corresponding names of fasta files can be found at metasample1/metaSpades/z_graphbin/bin_ids.csv

Thank you for using prepResult for GraphBin!

The file bin_ids.csv has this:
before_rr.fasta,1
contigs.fasta,2
first_pe_contigs.fasta,3
scaffolds.fasta,4

While the file initial_contig_bins.csv has this:
NODE_1,1
NODE_2,1
NODE_3,1
...
NODE_452809,4
NODE_452810,4

If I understood correctly, does this mean that all contigs belong to 4 bins?
Also, if this is correct which .gfa file should I use as input? SPAdes produces assembly_graph_after_simplification.gfa, assembly_graph_with_scaffolds.gfa, and strain_graph.gfa. I tried using all of them with contigs.paths and initial_contig_bins.csv 
and obtained the same error:
ERROR - Please make sure that you have provided the correct assembler type and the correct path to the binning result file in the correct format.

Sorry for the long post I am new to whole metagenomics, trying to catch up.

**Comment by Vini2** [comment]
Hello @FilipeMatteoli,

Thank you for posting this issue. The `prepResult.py` script is used to format the binning result obtained from an existing binning tool, not the original assembly. 

You should firstly bin the contigs found in the `contigs.fasta` file using some binning tool (e.g. MaxBin2, MetaWatt, CONCOCT, etc.). Normally these binning tools provide the contigs in fast files corresponding to each bin. You have to provide the folder with this binning result to the `prepResult.py` as the `--binned` parameter. Hope this clears out your issue.

Let me know if you have any further questions.

Thank you!
