### ISSUE TITLE
Conda release

### ISSUE THREAD

**Issue by vinisalazar** [Vini2/GraphBin#15]
Hi,

thank you for providing this package. I'm excited to use it.

Would you consider adding it a Conda repository such as Bioconda? I believe this would improve the installation process and make it more accessible for users.

I'd be glad to help drafting a recipe so the package can be added to Bioconda, if you agree.

Best wishes,
Vini

**Comment by Vini2** [comment]
Hi @vinisalazar,

I'm extremely sorry for getting back to you late.

We have been wanting to add a Conda recipe but never got the chance to do so. It would be great if you can help us to draft one. Let me know if this interests you.

Thank you!

Best regards,
Vijini

**Comment by vinisalazar** [comment]
Hi @Vini2, I also apologize for my late reply. I'll start working on it over the next few days and post here when I have an update. Thanks! :)

**Comment by vinisalazar** [comment]
I have drafted a recipe (please see the PR referenced above). If you could please review it (go to the PR page -> "Files changed" tab -> comment/approve/request changes), that would be great. Note that I have added both of us as recipe maintainers but feel free to remove me if you prefer.

Thank you!
V

**Comment by Vini2** [comment]
Hi @vinisalazar,

I have approved the merge. It seems that a maintainer needs to approve running workflows. I kept you as a maintainer. :) Thank you very much for drafting the recipe for GraphBin. 

Best regards,
Vijini

**Comment by vinisalazar** [comment]
My pleasure. Thanks again for providing this package!

Best wishes,
Vini
