### ISSUE TITLE
About the weights between two contigs

### ISSUE THREAD

**Issue by JLUVicent** [Vini2/GraphBin#18]
Hello!
Thanks for your research.I found that this research did not consider **the weight  between two contigs**.I wonder if **the weight** between two contigs has an **effect** on the final **clustering result**. At the same time,whether the connection between two contigs with weight can be generated through the script in this article.
Thanks!

**Comment by Vini2** [comment]
Hello @JLUVicent,

Thank you for raising this question. GraphBin only considers the graph topology for label propagation and the weight between two contigs is not considered. I believe the weight will definitely improve the final binning result. 

Currently, there is no script to generate the weights between contigs. However, my latest binning tool [MetaCoAG](https://github.com/Vini2/MetaCoAG) based on assembly graphs considers the weight between pairs of contigs. You can take a look at it. 

Hope this helps. Let me know if you have any questions.

Thank you!

Best regards,
Vijini

**Comment by JLUVicent** [comment]
I am very glad to receive your reply. Thank you!
