### ISSUE TITLE
Suggestion for prepResult.py

### ISSUE THREAD

**Issue by apcamargo** [Vini2/GraphBin#8]
Hi!

I've noticed that `prepResult.py` doesn't support `.fna` files, which is pretty common for bins. I'd be cool if support for this extension was added.

Also, I noticed that `subprocess` is not being imported into the script, causing a `NameError: name 'subprocess' is not defined` error.

**Comment by Vini2** [comment]
Hello @apcamargo!

Thank you very much for your suggestion. We will add support for `.fna` files in the future. Until then I will leave this issue open.

I fixed the missing import in `prepResult.py`. Thanks for pointing it out.

**Comment by Vini2** [comment]
Hello @apcamargo!

Thank you very much for your suggestion. I added support for `.fna` files in the `prepResult.py` script.
Commit ID: [1424dba14c8831f76f736e1a700af01a63e0bd66](https://github.com/Vini2/GraphBin/commit/1424dba14c8831f76f736e1a700af01a63e0bd66)

I also fixed the missing import in `prepResult.py` script. Thanks for pointing it out.

**Comment by apcamargo** [comment]
Thanks!

**Comment by Vini2** [comment]
Closing issue after incorporating suggestion.
